### ISSUE TITLE
No module named pycallgraph

### ISSUE THREAD

**Issue by irthomasthomas** [daneads/pycallgraph2#10]
Is this project still live? I'm having an issue getting it going. Docs say to run pycallgraph2 but this doesn't exist, and running pycallgraph instead produces the error "No module named pycallgraph".

 Cheers

**Comment by irthomasthomas** [comment]
The fix was easy enough. Just change the line in /usr/local/bin/pycallgraph to import pycallgraph2

**Comment by CromFr** [comment]
this has been fixed by PR #6, but there has been no release on pypi since

**Comment by daneads** [comment]
Thanks all, you should be able to update via today's PyPi release.
